### ISSUE TITLE
Fails to build on Win7-64bit

### ISSUE THREAD

**Issue by DileSoft** [kvark/vange-rs#104]
C:\Users\DileSoft\Documents\git\vange-rs>cargo run --bin convert
   Compiling wgpu-native v0.4.0 (https://github.com/gfx-rs/wgpu?rev=c293d6dcea0170bfa3835cfbd919f300560e0da6#c293d6dc)
error: linking with `link.exe` failed: exit code: 1181
>  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.0.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.1.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.10.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.11.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.12.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.13.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.14.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.15.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.2.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.3.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.4.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.5.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.6.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.7.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.8.rcgu.o" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.wgpu_native.a0tk6fl6-cgu.9.rcgu.o" "/OUT:C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.dll" "/DEF:C:\\Users\\DileSoft\\AppData\\Local\\Temp\\rustc8xFKoq\\lib.def" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.hahp4n539sk8lqc.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps" "/LIBPATH:C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\build\\spirv_cross-1ae9762af5ffce06\\out" "/LIBPATH:C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libwgpu_core-62d1e1df1179f92b.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libvec_map-a7eaa389c458d333.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\librendy_memory-508364ba3e8d7d8e.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libslab-37626b07ee31f03c.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libcolorful-8975d71a66d96c1f.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libhibitset-054b0592c062f459.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libatom-85e6b4708d481cdf.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libcopyless-38575204f954da8c.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libsmallvec-25a2ec483e24a253.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\librendy_descriptor-6a337f0a8356bb4b.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\librelevant-08bbf78e88518064.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_backend_vulkan-75f1f775e9f15a4c.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libarrayvec-9aabbc263375505b.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libash-a6e6a8cca66a5f6d.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libshared_library-181568997123a4c3.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\liblazy_static-8a754bbdc3482290.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_backend_empty-c36bc8cbc1670212.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_backend_dx12-ca6d2e1847e04a89.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libd3d12-d6f127ba80109ae3.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_backend_dx11-2203b9d57d47c1bd.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libwio-3dbd89cdb0bbbb9e.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libparking_lot-4fd925a65fdd3e15.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libparking_lot_core-8ee57e2a9be7d940.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\liblock_api-8d49351c58c6ac34.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libscopeguard-83cd82890024cd40.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\liblog-6bc263542d1548eb.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libcfg_if-fb26e8a2b6af24fc.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\liblibloading-0b0a438b580017c5.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libwinapi-7f5df6029d75c4b5.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\librange_alloc-f2738d87e5d9c91f.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_auxil-2fe13092d49dfe7c.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libfxhash-b921394e33bb52fe.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libbyteorder-b36a8bccb48c02aa.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libspirv_cross-382a119414fc029c.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libgfx_hal-34cdd7c6fda8b263.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libraw_window_handle-7257dd7ab7785c58.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\liblibc-df28af5f0c5d2814.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libsmallvec-93f90e493f6c3366.rlib" "C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\libbitflags-6412d77b3b137df6.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-f3cd9033b21bfd69.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-7177cc63e2247a71.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-dc4f9fa6045181bb.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-b42f2443bfe541d3.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-727167d019576e4a.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-b116c11df52ba1e2.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-d4c5a28b76348d5c.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-79bcbf9ce75fa48d.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-c9478dd7b586b8cc.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-c80eff7d74f3988c.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-fd0f5d5cd3b3863d.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-49f9f21b6d32d457.rlib" "C:\\Users\\DileSoft\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-b32ee8ba444e5f7c.rlib" "advapi32.lib" "comctl32.lib" "credui.lib" "d3d11.lib" "d3d12.lib" "d3dcompiler.lib" "dwmapi.lib" "dxgi.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "secur32.lib" "setupapi.lib" "shcore.lib" "shell32.lib" "shlwapi.lib" "synchronization.lib" "user32.lib" "uxtheme.lib" "winspool.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\Users\\DileSoft\\Documents\\git\\vange-rs\\target\\debug\\deps\\wgpu_native-611e3c6c2366f991.dll.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'd3d12.lib'

**Comment by DileSoft** [comment]
Tryed to change backend, no effect.

**Comment by kvark** [comment]
We figured this out: the lib comes with Visual Studio as a part of Windows 10 Kit on Windows 7... Finding this information on the internets is nearly impossible.
