### ISSUE TITLE
Can't build on windows, help with settings.ron

### ISSUE THREAD

**Issue by adsick** [kvark/vange-rs#128]
thread 'main' panicked at 'Can't find the resources of the original Vangers game at "/vange-rs-master/", please check your `config/settings.ron`', src\config\settings.rs:179:13

what does "original Vangers game" represent?
why just don't have default configuration to run cargo run and that's it?

**Comment by kvark** [comment]
Please see the top of README:
> You need the original game in order to try out vange-rs. The path to resources needs to be set in config/settings.ron.

See [original game](https://www.gog.com/game/vangers)

I can't put anything default in `settings.ron` because I don't know where you have the original installed.
