### ISSUE TITLE
Update repo config for the new domain

### ISSUE THREAD

**Issue by lolmaus** [kvark/vange-rs#132]
* [ ] Enforce HTTPS on the repo:

    https://github.com/kvark/vange-rs/settings

    <img src="https://user-images.githubusercontent.com/200884/101275592-c1820a80-37b7-11eb-8dc0-63cf956b7a63.png" width="400">

    If the checkbox is disabled for some reason, tell me and I will set up DNS redirects instead.

* [ ] Update website link in repo description:

    https://github.com/kvark/vange-rs
    
    <img src="https://user-images.githubusercontent.com/200884/101275647-35bcae00-37b8-11eb-95af-4d0367321602.png" width="400">

**Comment by lolmaus** [comment]
Please use the https://vange.rs URL. I have set up a DNS redirect from www to non-www.

**Comment by kvark** [comment]
Done, thank you!
