### ISSUE TITLE
Support GL backend: max_texture_dimension_2d = 8192

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#152]
Is it possible to change max_texture_dimension_2d to 8192? This is not mandatory because Chrome can start with 16384, but FF have limitation to 8192.

**Comment by kvark** [comment]
At the very least, we can make it work on levels that don't have 16K height. Only the main 3 levels are 16K.

**Comment by kvark** [comment]
Should be better with 7e74113e3643502bca78fbc1552d8f4ef2fc7e27
You'd need to switch the level to a smaller one in the config to actually run.
