### ISSUE TITLE
Support WebGL backend: Mismatch between texture format and sampler type

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#157]
Hi. Another error in WebGL after last update. 
**Chrome**
```
[.WebGL-0x1c740019f800] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).
```
**Firefox**
```
WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 0 is of type FLOAT, but the shader samples as UINT.
```

For both browsers, game renders only blue canvas

**Comment by kvark** [comment]
Do you have a place to host this? Or maybe you can use https://spector.babylonjs.com/ to see what texture is this, and how WebGL sees it initialized.

**Comment by caiiiycuk** [comment]
Sure, will do it asap.

**Comment by caiiiycuk** [comment]
Ha,ha :) I managed to compile it with emscripten and have exactly same error xD
![изображение](https://user-images.githubusercontent.com/1727152/143993273-f38b307b-7248-41aa-b20c-45beac0dd081.png)

**Comment by caiiiycuk** [comment]
Here it is. 

https://caiiiycuk.github.io/vangers-web/vange-rs/index.html 

Press go button, when blue screen is rendered it means that game run it's main loop.

**Comment by caiiiycuk** [comment]
![изображение](https://user-images.githubusercontent.com/1727152/144035844-32b1bee8-dd64-49cf-b954-e78485541e1b.png)

**Comment by caiiiycuk** [comment]
Text from picture:
[.WebGL-0xb372e00]GL ERROR :GL_INVALID_OPERATION : glDrawArraysInstancedANGLE: Texture bound to texture unit 0 with internal format GL_DEPTH_COMPONENT24_OES is not compatible with sampler type GL_UNSIGNED_INT_SAMPLER_2D
[.WebGL-0xb372e00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
14
[.WebGL-0xb372e00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Texture bound to texture unit 0 with internal format GL_DEPTH_COMPONENT24_OES is not compatible with sampler type GL_UNSIGNED_INT_SAMPLER_2D
170
[.WebGL-0xb372e00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Texture bound to texture unit 0 with internal format GL_DEPTH_COMPONENT24_OES is not compatible with sampler type GL_UNSIGNED_INT_SAMPLER_2D
road.js:1453 Uncaught (in promise) Error: Using exceptions for control flow, don't mind me. This isn't actually an error!

**Comment by caiiiycuk** [comment]
I imagine that it's hard to fix, so this instructions how to build emscripten version locally. I suggest to build emscripten version because it's easy to do. However it renders only two frames and then exit.

* Install [emsdk](https://emscripten.org/docs/getting_started/downloads.html)
* Check that `emcc` in in PATH
* `git checkout git@github.com:caiiiycuk/vange-rs.git`
* `cd vange-rs`
* `git checkout vange-rs-web-em`
* copy vangers data into `res_linux/data` folder
* `RUSTFLAGS="-C link-args=gxx_personality_v0_stub.o -C link-args=-s -C link-args=FULL_ES3=1 -C link-args=-s -C link-args=ALLOW_MEMORY_GROWTH=1 -C link-args=-s -C link-args=TOTAL_MEMORY=134217728" cargo build  --target wasm32-unknown-emscripten --bin road --verbose && cp target/wasm32-unknown-emscripten/debug/road* html5-emscripten`
* Run http server to sever `html5-emscripten` directory, and open it in browser

**Comment by caiiiycuk** [comment]
Additional you can enable additional traces of webgl using `-s` notation:
```
// Adds extra checks for error situations in the GL library. Can impact
// performance.
// [link]
var GL_ASSERTIONS = 0;

// If enabled, prints out all API calls to WebGL contexts. (*very* verbose)
// [link]
var TRACE_WEBGL_CALLS = 0;

// Enables more verbose debug printing of WebGL related operations. As with
// LIBRARY_DEBUG, this is toggleable at runtime with option GL.debug.
// [link]
var GL_DEBUG = 0;

// When enabled, sets preserveDrawingBuffer in the context, to allow tests to
// work (but adds overhead)
// [link]
var GL_TESTING = 0;
```

**Comment by caiiiycuk** [comment]
Complete traces
[console-export-2021-12-2_16-25-34.txt](https://github.com/kvark/vange-rs/files/7640696/console-export-2021-12-2_16-25-34.txt)

```
2 [Thread 1, GL ctx: 1]: bindBuffer(34962, [object WebGLBuffer]) -> undefined road.js:5559:97
1 [Thread 1, GL ctx: 1]: enableVertexAttribArray(0) -> undefined road.js:5558:89
5 [Thread 1, GL ctx: 1]: vertexAttribIPointer(0, 4, 5120, 12, 0) -> undefined road.js:5562:121
2 [Thread 1, GL ctx: 1]: vertexAttribDivisor(0, 0) -> undefined road.js:5559:97
WebGL warning: drawArraysInstanced: TEXTURE_2D at unit 0 is of type FLOAT, but the shader samples as UINT.
```

**Comment by kvark** [comment]
Thank you, that is lovely to see all the detail here!

**Comment by kvark** [comment]
I haven't verified this, but I believe #162 fixes it. The needed palette texture wasn't bound properly, and instead the shadow texture was there. This caused WebGL validation to scream at us.
