### ISSUE TITLE
WebGL: ERROR: Error in Adapter::request_device: Limit 'max_uniform_buffers_per_shader_stage' value 12 is better than allowed 11

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#159]
[caiiiycuk.github.io-1638270272168.log](https://github.com/kvark/vange-rs/files/7625218/caiiiycuk.github.io-1638270272168.log)

**Comment by caiiiycuk** [comment]
This problem is minor, I think it happens on really old GPU

**Comment by kvark** [comment]
Why would anybody report 11 uniform buffers available? that's quite surprising. We should just adjust the suggested webgl limits accordingly.

**Comment by caiiiycuk** [comment]
It's from UHD 605, reported by Maestro_D (Vangers public dev chat in telegram)

**Comment by kvark** [comment]
Filed https://github.com/gfx-rs/wgpu/pull/2235 to fix this

**Comment by kvark** [comment]
Fixed by #162
