### ISSUE TITLE
Game doesn't run

### ISSUE THREAD

**Issue by porky11** [kvark/vange-rs#16]
I get following error message:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:837`

**Comment by kvark** [comment]
(sorry for the late response!)
do you have the path to original game resources in `config/settings.toml`?

**Comment by porky11** [comment]
so I would need to have the original game to run this?

**Comment by kvark** [comment]
Yes, I think Readme states that. Perhaps, it should be communicated clearer?

I agree the error message should be improved as well.

**Comment by porky11** [comment]
`nano config/settings.toml # set the game path` is the only description, but it does not mention, that the game path is the path of the original game

**Comment by kvark** [comment]
@porky11 thanks, and sorry about the confusion!
This is now fixed in https://github.com/kvark/vange-rs/commit/035772b8b86f5e2de42a8079d153841ddf736e5e
