### ISSUE TITLE
WebGL: wasm32-unknown-unknown didn't render anything

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#166]
With latest updates there is no any WebGL error both on unknown/emscritpen path. However emscripten :champagne:  able to render something , but unknown have no frame updates. 

Emscripten output:
![изображение](https://user-images.githubusercontent.com/1727152/144787646-d57871f4-af46-4b00-a929-b7f8bc680993.png)

Unknown output:
![изображение](https://user-images.githubusercontent.com/1727152/144788392-46865296-8f87-4102-9676-1461f5a4c638.png)

It feels like even context is not created or never updated. At least spector.js didn't detect active context.

**Comment by caiiiycuk** [comment]
Even no blue screen that was in previous version.

**Comment by kvark** [comment]
That's pretty wild!

**Comment by caiiiycuk** [comment]
Fixed it! Just need to disable alpha channel on canvas.

**Comment by caiiiycuk** [comment]
Will polish this soon, will keep you posted. Thanks for amazing work!
