### ISSUE TITLE
Web Version: Terrible perfomance (cpu_step)

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#167]
~900 ms per each frame, 97% of time spent in `physics:step` function

![изображение](https://user-images.githubusercontent.com/1727152/144798259-e54daba3-98c6-4415-bfb7-35649a67ead0.png)
![изображение](https://user-images.githubusercontent.com/1727152/144798384-74e55236-eb8a-4aaf-a946-6fadf8bb481c.png)
![изображение](https://user-images.githubusercontent.com/1727152/144798423-b0b2c10f-c86f-4dea-8b4d-936c35fe49c5.png)
[vange-rs-profile(chrome).json.gz](https://github.com/kvark/vange-rs/files/7658508/vange-rs-profile.chrome.json.gz)

**Comment by kvark** [comment]
Why on earth would `cross` take a lot of time?
Do you have a link? I'd profile it on FF.

**Comment by caiiiycuk** [comment]
There are two places that I changed in game to work, maybe they affected performance. 

1) https://github.com/kvark/vange-rs/pull/149/files#diff-e58ec0edb03532e6e7809132781b6da92380f39f8ac4156623689f3910d71a5bR251

Constant delta 16, maybe it's too much or too small?

2) Not in PR (https://github.com/kvark/vange-rs/blob/HEAD/bin/road/game.rs#L508)
I changed spin_ver to 1.0, because I didn't get input from keyboard to work yet. Maybe this value is too high and physics goes crazy?

Regarding to link, yes I can do it, but I want to add true keyboard support first (maybe it can help to understand why it so).

**Comment by caiiiycuk** [comment]
Problem was solved when I pass real delta time

**Comment by kvark** [comment]
What delta were you passing?

**Comment by caiiiycuk** [comment]
https://github.com/caiiiycuk/vange-rs/blob/vange-rs-web/bin/boilerplate.rs#L267
Now I pass the real time delta, before I passed 16 which is wrong
