### ISSUE TITLE
WebGL: colors applied only on part of level

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#168]
If you try latest build everything seems very good, but the colors only applied on part of level (reproduces on all levels)

![image](https://user-images.githubusercontent.com/1727152/145199321-dcee2516-0862-4e94-bb63-de5b97d74f37.png)

Link to test:
https://caiiiycuk.github.io/vangers-web/vange-rs/

**Comment by kvark** [comment]
Thank you for filing! I'd love to have a workflow for debugging WebGL.
It's so much easier with WebGPU...

**Comment by kvark** [comment]
Maybe we can have an input box with the terrain fragment shader? So I can tweak it and see how the rendering responds?

**Comment by caiiiycuk** [comment]
Sure, I can do this, should be simple.

**Comment by caiiiycuk** [comment]
Now you can change shaders without rebuilding project. Just download [release zip](https://github.com/caiiiycuk/vange-rs/releases/tag/v1.0-alpha), extract it somewhere and start webserver to server it.

Then you can change files in asstes/res folder and reload page (just ensure that you disable cache in browser).

**Comment by kvark** [comment]
Thanks to this, issue is fixed in 664e25bf4f377f2f52d1803c8ed37cabd5d67c91

**Comment by caiiiycuk** [comment]
So cool! I will prepare PR to merge.
