### ISSUE TITLE
Optimize Splay::decompress

### ISSUE THREAD

**Issue by kvark** [kvark/vange-rs#17]
This is our bottleneck for level loading performance in Debug. It'd be great to make it fast in order to have faster dev cycles.

**Comment by kvark** [comment]
An extreme approach would be moving `splay` into a separate crate, with tests, benchmarking, and such.

**Comment by kvark** [comment]
Proposals to investigate:
  - something different for the output stream than current `&mut [u8]` + index
  - something different for the input than current `&mut Read`
  - pack the tree characters into the high bits of tree indices. Actually, just generate the chars on the fly with `(!v as u8).wrapping_add(1)`

**Comment by lpenguin** [comment]
May be the simplest way is to decode level file once and save it as raw heightmap without compression.
