### ISSUE TITLE
vange-rs not working anymore (Intel HD): unknown attribute: 'block'

### ISSUE THREAD

**Issue by caiiiycuk** [kvark/vange-rs#177]
Just trying to build and run master branch.
Video: Intel Corporation HD Graphics 620 (rev 02)
Shader error:
```
Caused by:
    In Device::create_shader_module
      note: label = `object`
    
Shader 'object' parsing error: unknown attribute: 'block'
   ┌─ wgsl:55:3
   │
55 │ [[block]]
   │   ^^^^^ unknown attribute


    unknown attribute: 'block'
```

[backtrace.log](https://github.com/kvark/vange-rs/files/7869868/backtrace.log)
[debug.log](https://github.com/kvark/vange-rs/files/7869870/debug.log)

**Comment by kvark** [comment]
Please provide your `git` revision and the configuration.

**Comment by caiiiycuk** [comment]
Sorry, I messed up with resources, I copied res over existing res directory and so it's not work. After clearing res directory everything is work. :+1:
