### ISSUE TITLE
Second layer rendered wrong

### ISSUE THREAD

**Issue by DileSoft** [kvark/vange-rs#178]
![image](https://user-images.githubusercontent.com/964238/149629052-164f21af-8580-4564-9e1f-a7e8e503f3d9.png)

**Comment by kvark** [comment]
Thanks for filing!
Fixed in 97baed4

**Comment by kvark** [comment]
![vangers-fixed-double-level](https://user-images.githubusercontent.com/107301/149648481-b0c63a21-858d-4d78-8f23-91f096ec1eb0.jpg)
