### ISSUE TITLE
Physics module from original game

### ISSUE THREAD

**Issue by kvark** [kvark/vange-rs#18]
We should have an ability to use the original physics as well as roll in our own.
The original code is quite complex, but the main problem comes from axiomatic differences that make any comparison difficult:
  - left-handed coordinate system (X cross Y == -Z)
  - row-major matrices

**Comment by stalkerg** [comment]
I think we can post links to the Vangers source code here, where is exist physics logic.

**Comment by kvark** [comment]
This is done with #90, finally
