### ISSUE TITLE
Добавить поддержку просмотра эскейвов

### ISSUE THREAD

**Issue by DileSoft** [kvark/vange-rs#184]
![image](https://user-images.githubusercontent.com/964238/150567505-6c4d82ff-745c-485e-b366-387bb849ea74.png)

Сейчас при открытии через surmap в режиме 3d, неправильно отображается палитра. Хорошо бы также чтобы vange-rs мог самостоятельно показывать эскейвы.

**Comment by kvark** [comment]
General 16-wide palette rendering is implemented in 7c766afce51936b3d67162bda0daedfc74b3c1a8
Support for `level` tool is in bbccaa0895c0bd449a9a7ae013a7c02b4a277f06 (latest).
Example invocation is in README:
```bash
cargo run --bin level -- resource/iscreen/ldata/l0/escave.ini
```
Full path also works (for me on Linux, at least)

**Comment by kvark** [comment]
![vangers-menu-1](https://user-images.githubusercontent.com/107301/150622085-71b7b502-e9cb-4b05-824a-1e99fd93c989.jpg)
