### ISSUE TITLE
Уровни отражены по вертикали

### ISSUE THREAD

**Issue by DileSoft** [kvark/vange-rs#185]
![image](https://user-images.githubusercontent.com/964238/150629494-b0382610-1ac5-44e3-ab33-72435efcc98a.png)
![image](https://user-images.githubusercontent.com/964238/150629495-af06ca1f-8c22-48f2-8340-bee8bffcedb0.png)

**Comment by kvark** [comment]
I'm still not totally sure where and why the bug happens. After all, the level as rendered in the `road` binary is looking finely oriented.

**Comment by kvark** [comment]
Fixed in e30ef97f32cedc4c04ac0d2e533dd441e7ba4309
