### ISSUE TITLE
FFI: rv_render: viewport rect is not handled correctly

### ISSUE THREAD

**Issue by lpenguin** [kvark/vange-rs#195]
It doesn't render a center of the view into the viewport and behaves more like a scissors.

One can reproduce this bug in rv_ffi (commit https://github.com/lpenguin/rv_ffi/commit/9564839641c8ae3fa45541f35d22fb4dd3259eed). Use arrow keys to modify the viewport.

Full rect viewport
![изображение](https://user-images.githubusercontent.com/564449/151536428-0ce4f04c-f7fd-4d23-9207-8b9d32fb3a8e.png)
Half rect viewport
![изображение](https://user-images.githubusercontent.com/564449/151536452-42ca03cf-fe8b-46ef-8436-88bf248f08ed.png)

**Comment by kvark** [comment]
Thanks for the issue!
Fixed in 481e549a22331a5b71bcffd00d978c46ae3c85ef
