### ISSUE TITLE
Добавить поддержку браузеров/видеокарт с текстурами меньше 16000

### ISSUE THREAD

**Issue by DileSoft** [kvark/vange-rs#200]
Например хранить данные не в одной большой текстуре, а в нескольких.

**Comment by kvark** [comment]
One interesting choice here is mentioned as the last point of #199 : turn the texture sideways and pack 2 texels into one. This would mean we can support 16K size naturally in WebGPU baseline, and it wouldn't require any texture coordinate transformation for texture arrays. However, once we go this path, we wouldn't be able to do linear interpolation between heights - and that's something I'd like to try out.
