### ISSUE TITLE
Vangers don't support macos m1?

### ISSUE THREAD

**Issue by ZhangHanDong** [kvark/vange-rs#204]
I installed the GOG Vangers game on my m1, but the window flashed when I ran it, I checked the logs:

```
Joystick not found
```

And,  the data configuration in config/settings.ron under macosx m1 is not `/Applications/GOG/Vangers.app/Contents/Resources/game`, I don't know how to set this path.

**Comment by kvark** [comment]
It sounds like you are talking about the original game, not vange-rs.
Perhaps, you meant to file it to https://github.com/KranX/Vangers instead?
