### ISSUE TITLE
Consider Three-rs for the engine

### ISSUE THREAD

**Issue by kvark** [kvark/vange-rs#21]
https://github.com/three-rs/three

**Comment by kvark** [comment]
@vitvakatu the game is now struggling to cope with all the draw calls as of https://github.com/kvark/vange-rs/commit/c216965c9a265a41883986bad874ad5e32f184dd if I set the NPC count to anything higher than 100. We need that auto-instancing (https://github.com/three-rs/three/pull/150) of Three-rs badly :)

**Comment by vitvakatu** [comment]
It will be there today :wink:

**Comment by kvark** [comment]
It appears that the GPU usage in vange-rs is moving away from the standard abstractable object drawing to more customized solutions, e.g. https://github.com/kvark/vange-rs/pull/45
On this note, I'm going to close the issue, but open to ideas about re-considering it.
