### ISSUE TITLE
dependency error: "Edition 2018 is unstable and only available for nightly builds of rustc."

### ISSUE THREAD

**Issue by NIR-Ginko** [kvark/vange-rs#67]
I'm experiencing problems building the program with `rustc` version `1.30.1` (commit `1433507eb`) on FreeBSD 11.2 on AMD64:
```
Compiling stb_truetype v0.2.5
error: Edition 2018 is unstable and only available for nightly builds of rustc.

error: Could not compile `stb_truetype`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Is it possible to lock the version of the package to the one that does not require `Rust 2018 edition` in order to build the program?

**Comment by kvark** [comment]
You can just change the root `Cargo.toml` by adding those dependencies with fixed versions, e.g.
```toml
stb_truetype = "=0.2.2"
```

**Comment by NIR-Ginko** [comment]
I found that insalling `nightly-` toolchain and invoking `cargo +nightly build` solves the problem so just closing the issue.

**Comment by kvark** [comment]
Sorry for a stupid question, but did you also try `rustup update` and run the stable?

**Comment by NIR-Ginko** [comment]
I can't remember if did this really. Anyway thanks for the help - I like the project and find it useful but there is not much I can help with.

**Comment by kvark** [comment]
@NIR-Ginko if interested, please pop in https://gitter.im/vange-rs/Lobby . I'd be happy to discuss the future plans as well as possible areas to help with ;) There is a lot that can be done here.
